print(" welcome to code chat !")
name = input("whats your name")
print( f"nice to meet you {name}")
age = input(" what is your age")
print(f"oh cool {name} is {age} years old")
print("hello" , end=" ")
print("will \nmy in game name is juicyacer")

print(" welcome to the chat!")
name = input(" whats your name?")
print(f"good to meet you {name}.")
age = input(" what is your age ?")
print(f"oh nice {name} is {age} years old.")
print(" hi" , end=" ")
print(f" {name} \nmy online name is juicyacer.")
favgame = input("whats your favorite video game?")
print(f"awesome {favgame} is a good one.")
print(" my favorite video game is minecraft.")
food = input(" whats your favorite food?")
print(f"yeah {food} is delicious!")
print(f"well it was nice talking to you {name}.")
print(" have a good one.")